### ISSUE TITLE
Add ability to reload configuration file

### ISSUE THREAD

**Issue by dchidell** [TwinProduction/gatus#92] opened 2021-03-05 00:22 UTC
I use a custom service which performs automated discovery for importing services into gatus.

The problem is there's no easy way to reload this configuration - I am currently just restarting the container, which works, but isn't a great solution.

It would be great to have some way to reload the config, perhaps either via a GET request to a particular endpoint, or a signal (SIGHUP?) to trigger a reload.

**Comment by TwinProduction** [comment] 2021-03-05 02:24
Duplicate of #29

**Closed by TwinProduction** 2021-03-05 02:24 UTC
Labels: duplicate
