### ISSUE TITLE
vague error "server misbehaving"

### ISSUE THREAD

**Issue by hurnhu** [TwinProduction/gatus#27] opened 2020-11-09 16:04 UTC
On a single site I get this error.
From my quick googling "server misbehaving" seems to be an dns error with go?

Maybe if that error occurs a second try for the sit should be done before marking the site as failing?
Out of out 35 sites theres only one that does this.

Or at least give a better error message than this, something like "DNS error". 

![image](https://user-images.githubusercontent.com/3117181/98564937-fcf1ed80-227a-11eb-96d2-daad6819de40.png)

**Comment by TwinProduction** [comment] 2020-11-09 18:49
Hello @hurnhu and thank you for raising this issue.

While I agree that `server misbehaving` is quite an odd error, I'd rather avoid tampering with the errors, as these errors themselves may lead to resolving the issues and replacing `server misbehaving` by `DNS error` might also make it harder to pinpoint the cause.

That being said, if you're able to provide me with a way to reproduce this locally, I can look into it more closely.

**Closed** 2020-11-14 21:36 UTC
