### ISSUE TITLE
Failed to read storage file

### ISSUE THREAD

**Issue by dchidell** [TwinProduction/gatus#93] opened 2021-03-06 13:38 UTC
This might be better described as two issues - but it's likely they're interrelated.

Running via docker, issue is impacting the v2.1.0, v2.2.0 and latest tags (digest d023d2d92447 as of writing).

I'm monitoring 52 services, and 29 of them are utilising the `pat` function to check that the response actually contains what it's supposed to. The check interval is the default of 60s. I have persistent storage enabled.

I've been running gatus for around 1 week, and this has resulted in the storage file growing to ~128mb in size, seemingly as the http results are all being stored. I am now getting the below stacktrace when attempting to start gatus.

I can provide the history file if required, but would prefer to share it privately as it contains a number of details from internal services.

```

2021/03/06 13:07:26 [config][Load] Reading configuration from configFile=config/config.yaml
2021/03/06 13:07:26 [config][validateAlertingConfig] Alerting is not configured
2021/03/06 13:07:26 [config][validateServicesConfig] Validated 52 services
2021/03/06 13:07:26 [storage][Initialize] Creating storage provider with file=/config/history
panic: gob: wrong type (map[int64]uint64) for received field Uptime.SuccessCountPerHour
goroutine 1 [running]:
github.com/TwinProduction/gatus/config.validateStorageConfig(0xc00007c050)
	/app/config/config.go:163 +0x2c5
github.com/TwinProduction/gatus/config.parseAndValidateConfigBytes(0xc00041e000, 0x1b7d, 0x1b7e, 0x1b7d, 0x1b7e, 0x0)
	/app/config/config.go:152 +0x1a5
github.com/TwinProduction/gatus/config.readConfigurationFile(0x15f8237, 0x12, 0xc000187e88, 0x1, 0x1)
	/app/config/config.go:128 +0x8a
github.com/TwinProduction/gatus/config.Load(0x15f8237, 0x12, 0x11, 0x0)
	/app/config/config.go:101 +0xa8
github.com/TwinProduction/gatus/config.LoadDefaultConfiguration(0x15f696a, 0x11)
	/app/config/config.go:114 +0x3a
main.loadConfiguration(0xc00005c748)
	/app/main.go:43 +0x86
main.main()
	/app/main.go:16 +0x26
```

**Comment by TwinProduction** [comment] 2021-03-06 19:36
@dchidell By any chance, are you using the `latest` Docker tag?

I've made a change that significantly improved the performance of the uptime computation, but at the cost of a breaking change for those using storage.

Furthermore, this change was necessary for two things:
1. Reducing the performance impact caused by increasing the maximum result history
2. Preparing for a feature that would display a calendar with the uptime of each service over the past several days, potentially even months

This is the change in question: https://github.com/TwinProduction/gatus/commit/6320237326c87803ebc71011b80e98d5b8d941ea

I was planning on writing a note in the next release about this, but I guess there are quite a few people using the latest tag instead of a stable version 😅

Since the persistence feature is relatively new, I assumed that the impact would be negligible, alas, it seems it wasn't.

Anyways, this leaves you with two choices:
1. Use the version `v2.2.0` instead of `latest`
2. Delete the file and start with a fresh dashboard

Personally, I suggest you go for the second option, as the dashboard will be rather quickly repopulated considering you use an interval of 60s, but the choice is yours.

**Comment by TwinProduction** [comment] 2021-03-06 20:25
I found a way to avoid having to call this a "breaking change".
The only downside is that the uptime history will be not survive the transition, but everything else does, so in the grand scheme of things, this is a lot better.

@dchidell I've tried it locally, but could you try it on your end too and tell me how it went?

**Comment by dchidell** [comment] 2021-03-06 20:54
Looks good! Superb job resolving that so fast.

Guilty as charged for using the latest tag - and having them automatically upgrade at 4am, but it leads to a more exciting life!

**Comment by TwinProduction** [comment] 2021-03-06 22:11
Hahaha don't worry about it, I'm also guilty for making a breaking change knowing that a lot of users were using the latest tag in the first place :P

Since the issue is resolved, I'm going to close this issue.

**Closed by TwinProduction** 2021-03-06 22:11 UTC
Labels: bug
