### ISSUE TITLE
Filter & columns ?

### ISSUE THREAD

**Issue by m4dm4rtig4n** [TwinProduction/gatus#168] opened 2021-09-06 14:45 UTC
Hi, 

I have a lot of group (21) and services (84) and the navigation is quite tedious.

I find it would be very handy to be able to:
- Filter services by state
- Have the possibility of having multiple columns

**Comment by TwinProduction** [comment] 2021-09-06 17:27
Kind of a duplicate of #35. Would you mind adding your suggestions as a comment in that issue @m4dm4rtig4n?

**Closed by TwinProduction** 2021-09-06 17:27 UTC
