### ISSUE TITLE
failed service interval

### ISSUE THREAD

**Issue by rebelga** [TwinProduction/gatus#119] opened 2021-06-03 14:06 UTC
It would be helpful if a different interval could be specified for when a service is in a failed state.

I run 5m intervals on some services but would like to check more frequently when they are failed.

**Comment by TwinProduction** [comment] 2021-06-03 23:47
Duplicate of #112

If you'd like to show your interest in the feature, I suggest you 👍 the aforementioned issue, as I tend to prioritize feature requests based on the interest they garner.

**Closed by TwinProduction** 2021-06-03 23:47 UTC
